namespace: eledio
name: services
version: 1.0.0
readme: README.md

authors:
  - Richard Kubíček <richard.kubicek@eledio.com>

description: Ansible roles for deploying and managing services on Debian-based systems (including Raspberry Pi OS)

license:
  - GPL-2.0-or-later

tags:
  - debian
  - raspberry
  - iot
  - manufacturing

dependencies: {}

repository: https://github.com/eledio-manufacturing/ansible-services.git
homepage: https://github.com/eledio-manufacturing/ansible-services
issues: https://github.com/eledio-manufacturing/ansible-services/issues

build_ignore:
  - "*.orig"
  - .venv
  - __pycache__
