---
- name: Check if uv is already installed
  ansible.builtin.stat:
    path: "{{ install_uv_install_dir }}/uv"
  register: install_uv_binary

- name: Download uv installer
  ansible.builtin.get_url:
    url: https://astral.sh/uv/install.sh
    dest: /tmp/uv-install.sh
    mode: '0755'
  when: not install_uv_binary.stat.exists

- name: Install uv
  ansible.builtin.command: /tmp/uv-install.sh
  args:
    creates: "{{ install_uv_install_dir }}/uv"
  environment:
    INSTALLER_NO_MODIFY_PATH: "1"
    UV_INSTALL_DIR: "{{ install_uv_install_dir }}"
  when: not install_uv_binary.stat.exists

- name: Remove uv installer
  ansible.builtin.file:
    path: /tmp/uv-install.sh
    state: absent
  when: not install_uv_binary.stat.exists
