---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  listen: Restart printer

- name: Restart printer service
  ansible.builtin.systemd:
    name: printer
    state: restarted
  listen: Restart printer
